version: "1.1"

services:
  postgres:
    image: postgres:14.5
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "testdb"
    volumes:
      - project:/var/lib/postgresql/data
      - /data/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - /data/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      - project
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - project
  project:
    container_name: project
    image: docker.io/library/article-postgres-1
    expose:
      - "8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      DATABASESERVER_PORT: "5432"
    depends_on:
      postgres:
        condition: service_started
    networks:
      - project
networks:
  project:
    driver: bridge
volumes:
  project:
    driver: local
  pgadmin-data:
    driver: local